steps:
  - name: 'node:22-alpine'
    dir: 'client'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'npm install && npm run build'

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'docker build -t gcr.io/$PROJECT_ID/hafnerp-dev:$COMMIT_SHA .'
      - 'docker push gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY