steps:
  - name: 'node:22-alpine'
    dir: 'client'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'npm install && npm run build'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['login', '-u', 'oauth2accesstoken', '-p', '$(gcloud auth print-access-token)', 'gcr.io']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

substitutions:
  _SERVICE_NAME: 'hafnerp-dev'

options:
  logging: CLOUD_LOGGING_ONLY
